#name: Playwright Tests
#on:
#  push:
#    branches: [ main, master ]
#  pull_request:
#    branches: [ main, master ]
#jobs:
#  playwright-test:
#    timeout-minutes: 60
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v5
#      - name: Setup Node.js environment
#        uses: actions/setup-node@v5
#        with:
#          node-version: 22
#      - name: Install pnpm
#        uses: pnpm/action-setup@v4
#        with:
#          version: 10
#      - name: Install dependencies
#        run: pnpm install
#      - name: Install Playwright Browsers
#        run: pnpm exec playwright install --with-deps
#      - name: Run Playwright tests
#        env:
#          OPEN_WEATHER_API_URL: ${{ secrets.OPEN_WEATHER_API_URL }}
#          OPEN_WEATHER_API_KEY: ${{ secrets.OPEN_WEATHER_API_KEY }}
#        run: pnpm run test:e2e
#      - uses: actions/upload-artifact@v4
#        if: ${{ !cancelled() }}
#        with:
#          name: playwright-report
#          path: playwright-report/
#          retention-days: 30